// AO_Log.cpp

#include "AO_Log.h"
#include "Modules/ModuleManager.h"

DEFINE_LOG_CATEGORY(LogKH);
DEFINE_LOG_CATEGORY(LogJM);
DEFINE_LOG_CATEGORY(LogHSJ);
DEFINE_LOG_CATEGORY(LogJSH);
DEFINE_LOG_CATEGORY(LogKSJ);
DEFINE_LOG_CATEGORY(LogKSH);
